### ISSUE TITLE
two different syntaxes of product name make failling om-cli configure-product

### ISSUE THREAD

**Issue by kecirlotfi** [pivotalservices/tile-config-generator#14]
Hello 
We're using tile-config-generator to configure our tiles. We noticed that the entry defining the product name was added with two different syntaxes as you can see it below.
product_name: cf
product-name: cf
product_version: 2.1.17
But when we use the new version of om cli (version 0.46.0), this makes om configure-product fail because it doesn't support about this entry product_name.
Regards

**Comment by calebwashburn** [comment]
Can you provide the entire error message that you are getting from `om`.  `product_name` and `product-name` were being duplicated to ensure backward compatiblity

**Comment by calebwashburn** [comment]
Removed in 0.0.12 - https://github.com/pivotalservices/tile-config-generator/releases/tag/v0.0.12

**Comment by kecirlotfi** [comment]
I confirm this solved the issue. 

Thanks and sorry for my delayed reply.
