### ISSUE TITLE
Array entries not always handled correctly

### ISSUE THREAD

**Issue by kecirlotfi** [pivotalservices/tile-config-generator#15]
we are facing this issue with RabbitMQ for PCF tile.

We have to specify a list for the following variables:
* rabbitmq-server/ssl_versions
* rabbitmq-server/plugins

However, in the product.yml file generated, these variables are expected to be strings.
As a result, after doing a "bosh interpolate", we end up with "- -" strings instead of "-" in front of the first array element.

**Comment by calebwashburn** [comment]
What version of rabbit mq tile?  Which version of tile-config-generator?  What is the output that is produced?

**Comment by kecirlotfi** [comment]
I'm using version 0.0.10
I noticed that there is a new version that was issued 2 hours ago. I'm going to try it and give a feedback. thank you.

**Comment by calebwashburn** [comment]
yes, sorry 0.0.10 is broken for rabbit-mq.  Will remove that release.
