### ISSUE TITLE
Missing backups_selector property for MySql

### ISSUE THREAD

**Issue by tonyelmore** [pivotalservices/tile-config-generator#17]
**Describe the bug**
Missing property for MySql tile when adding `features/backups_selector-azure.yml` 

Error: `Expected to find a map key '.properties.backups_selector' for path '/product-properties/.properties.backups_selector'`

**Expected behavior**
backups_selector property should be in product.yml

**Version info**
 - tile-config-generator: 0.0.13
 - tile MySql
 - tile-version 2.3.1 & 2.4.1

**Additional context**

**Comment by calebwashburn** [comment]
Please validate using 0.0.13 of tile-config generator as was able to generate and do the following interpolation without any issues on 0.0.13 

```
~/Downloads/tile-config-generator-osx version                                                                                 master
v0.0.13-1c3dc24f7addc0cf32b91a1431380e453aaf1857
```

```
bosh int pivotal-mysql/2.4.1-build.28/product.yml --ops-file pivotal-mysql/2.4.1-build.28/features/backups_selector-azure.yml
```

**Comment by tonyelmore** [comment]
V 0.0.13 worked
