### ISSUE TITLE
Could an empty product-default-vars.yml be created when no default vars

### ISSUE THREAD

**Issue by tonyelmore** [pivotalservices/tile-config-generator#18]
**Describe the bug**
When a product does not have any default vars a product-default-vars file is not created.  However, when using automation to build pipelines, it would be beneficial that the file exists in order to not have to create special handling for the scenarios when the file does not exist.

**Expected behavior**
Create an empty product-default-vars.yml file

**Screenshots**

**Version info (please complete the following information):**
 - tile-config-generator: 0.0.13
 - tile SSO (maybe others)
 - tile-version 1.7.2

**Additional context**
We have a template that is used to build the final pipeline and builds the upload/stage/config section for every tile.  The template references all of the var files generated by TCG.

**Comment by calebwashburn** [comment]
Fixed in 0.0.14
