### ISSUE TITLE
tile-config-generator doesn't seem to understand tildas (~) in file paths

### ISSUE THREAD

**Issue by dav1dc-pcf** [pivotalservices/tile-config-generator#19]
**Describe the bug**
```
$ tile-config-generator generate --pivotal-file-path=~/Downloads/pivotal-container-service-1.3.0-build.38.pivotal --base-directory=~/tmp/src/pks-tile-config-generator --do-not-include-product-version
error: open ~/Downloads/pivotal-container-service-1.3.0-build.38.pivotal: no such file or directory
$ ls -l ~/Downloads/pivotal-container-service-1.3.0-build.38.pivotal
-rw-r--r--@ 1 user  staff  4308256645 Jan 25 10:31 /Users/user/Downloads/pivotal-container-service-1.3.0-build.38.pivotal
```

**Expected behavior**
I was hoping that the binary would understand the meaning of tilda (~) in file paths provide via command line switches

**Version info (please complete the following information):**
 - tile-config-generator: 0.0.14
 - tile pivotal-container-service
 - tile-version 1.3.0

Work around was to expand the ~, replacing it with the absolute path to the tile.

**Comment by calebwashburn** [comment]
The functionality of this tool has been moved into the officially supported `om` tooling.  https://github.com/pivotalservices/tile-config-generator/blob/master/README.md#deprecation-notice Please re-open this issue in that repository as that will get prioritize by team focusing on the future development.
