### ISSUE TITLE
Value float64 is not known - ECS Service Broker Tile

### ISSUE THREAD

**Issue by bennerv** [pivotalservices/tile-config-generator#22]
**Describe the bug**
When attempting to generate the configuration for the Dell ECS tile using the below command, the binary fails with the error: `error: Value float64 is not known` . This happens on both MacOS and Linux (Ubuntu 16.04) 

`./tile-config-generator-osx generate --base-directory=. --include-errands --token=$PIVNET_TOKEN --product-slug=ecs-service-broker --product-version=1.2.1 --product-glob=*.pivotal`

**Expected behavior**
Expect to be able to generate the configuration for the Dell ECS tile.

**Screenshots**

**Version info (please complete the following information):**
 - tile-config-generator: v0.0.15
 - tile: ecs-service-broker
 - tile-version: 1.2.1

**Additional context**
When tracing the issue back to code, the issue lies in the file `collection_property_metadata.go`.  The array property value attempting to be set is of type float64, which is not one of the valid types that can be used (string, bool, int).  Was able to temporarily work around this issue by creating a SimpleFloat64 type in `value_types.go` and adding a case statement for float64.  

Additionally, when debugging the tile tile with the above command, it was determined that the below properties, keys, and values were the cause of this issue.

This may not be an issue with the tile generator itself, but with the Dell ECS tile having an unsupported configuration type.  

```
Properties: 
propertyName: "catalog_plan_collection0_0"
key: "cost_usd"
value: 0 (float64)

propertyName: "catalog_plan_collection0_0"
key: "cost_usd"
value: 0.03 (float64)

propertyName: "catalog_plan_collection1_0"
key: "cost_usd"
value: 0 (float64)

propertyName: "catalog_plan_collection1_0"
key: "cost_usd"
value: 0.03 (float64)

propertyName: "catalog_plan_collection2_0"
key: "cost_usd"
value: 0 (float64)

propertyName: "catalog_plan_collection2_0"
key: "cost_usd"
value: 0.03 (float64)

propertyName: "catalog_plan_collection3_0"
key: "cost_usd"
value: 0 (float64)

propertyName: "catalog_plan_collection3_0"
key: "cost_usd"
value: 0.03 (float64)

propertyName: "catalog_plan_collection4_0"
key: "cost_usd"
value: 0 (float64)

propertyName: "catalog_plan_collection4_0"
key: "cost_usd"
value: 0.03 (float64)
```

**Comment by calebwashburn** [comment]
This should be fixed in 0.0.16 release.  I didn't follow your last piece of information about `value: 0 (float64)`.  Now that error is resolved if the files generated are not able to be successfully used to configure the tile please open a different issue show the output of `om staged-config` for a tile deployment that is manually installed
