### ISSUE TITLE
when downloading with pivnet with non existing version creates empty scaffold

### ISSUE THREAD

**Issue by ramonskie** [pivotalservices/tile-config-generator#23]
when i try to run the following
`tile-config-generator generate --token xxxxxxxxxx --product-slug=elastic-runtime --product-version=2.5 --product-glob='srt*.pivotal' --base-directory tmp/

it will generate a empty scaffold.
no error is raised

**Comment by calebwashburn** [comment]
The functionality of this tool has been moved into the officially supported `om` tooling.  https://github.com/pivotalservices/tile-config-generator/blob/master/README.md#deprecation-notice Please re-open this issue in that repository as that will get prioritize by team focusing on the future development.
