### ISSUE TITLE
does not handle cf 2.2.2-build.2

### ISSUE THREAD

**Issue by fredwangwang** [pivotalservices/tile-config-generator#6]
tile: pas
version: 2.2.2-build.2
tool version: c95b89755514a58bf75039a865bd76e91971ca59
command ran: `go run cmd/tile-config-generator/main.go generate --base-directory cf --pivotal-file-path ~/Downloads/cf-2.2.2-build.2.pivotal`
issue: Unable to find option template for .properties.router_client_cert_validation.request

**Comment by calebwashburn** [comment]
This is actually due to a bug in 2.2.2 tile metadata that I reported.  The message is just a warning.

https://www.pivotaltracker.com/n/projects/975916/stories/159204676

**Comment by fredwangwang** [comment]
clearly I didn't run `echo $?` to verify if it returns 0..
