### ISSUE TITLE
using kiln's struct definition instead?

### ISSUE THREAD

**Issue by fredwangwang** [pivotalservices/tile-config-generator#9]
the package `github.com/pivotal-cf/kiln/proofing` has everything defined to work with tile metadata, the struct defined in this project is basically a subset of the definitaion. What about just switch to kiln's package directly?

[This](https://github.com/pivotal-cf/kiln/blob/master/proofing/product_template.go) for example, already decode a lot metadata information.

There are several benefits I could think of, mainly:
* Reduce maintance, don't need to keep the structs up-to-date with metadata schema, as kiln should do that.
* Easy to extend, kiln's definition should be the most feature-rich one for golang, as it is the tool for making tiles
* Delete some code

**Comment by calebwashburn** [comment]
That's good feedback.  Didn't even know that library existed...

**Comment by fredwangwang** [comment]
I can do a PR if you want, since I haven’t played with both tools much, might be interesting to dig into the code a little bit

**Comment by calebwashburn** [comment]
That would be great!

**Comment by fredwangwang** [comment]
Nah... Actually I am going to close this issue without any substantial work done. It's not as straightforward as I thought it would be. Main difficulty is that `kiln/proofing` does not provide any method on those structs.

In order to use their struct and provide additional method, there are basically two ways:
1. inheritance
eg. `type NewStruct { OriginalStruct }`. It is doable if the number of structs is small, but when there are a lot of structs (~10 in this case), it becomes a mess.

1. use function instead of method
This is straightforward, but requires basically rewrite(restyle) the entire project, doesn't seems like worth doing.

Either way doesn't seem like a good enough solution...
